version: "3.9"

services:
  db:
    image: postgres:16
    container_name: despesas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: despesas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_despesas:/var/lib/postgresql/data

volumes:
  pgdata_despesas:
