services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_class
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

# PostgreSQL 18 (opcional para testes em versões mais novas)
# image: postgres:18
# services:
#   db:
#     image: postgres:18
#     restart: unless-stopped

#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: backend_class

#     ports:
#       - "5432:5432"

#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: